platform :ios, "7.0"

pod "AFNetworking", "~> 3.0"
pod 'Toast', '~> 3.0'
pod 'JDStatusBarNotification'
pod 'TWMessageBarManager'


# target :<#TargetName#>Tests, :exclusive => true do
  # pod 'Kiwi'
# end
